fix for uninitialized partition

diff --git a/csphere/csphere/files/cosversion b/csphere/csphere/files/cosversion
--- a/csphere/csphere/files/cosversion
+++ b/csphere/csphere/files/cosversion
@@ -24,16 +24,20 @@ elif [[ "${active_dev}" =~ 4$ ]]; then
 	inactive_dev="${active_dev/%4/3}"
 fi
 inactive_flb=$(blkid -o udev "${inactive_dev}" 2>&- | awk -F= '/^ID_FS_PARTLABEL/{gsub(" ","",$2);print $2}')
-tmpdir=$(mktemp -d)
-errstr=$(mount -o ro ${inactive_dev} ${tmpdir} 2>&1 1>/dev/null)
-if [ $? -eq 0 ]; then
-	inactive_ver=$(awk -F= '/VERSION=/{print $2}' ${tmpdir}/${path} 2>&-)
-	umount ${tmpdir}
-	rmdir ${tmpdir}
+if ( tune2fs -l "${inactive_dev}" 2>&1 | grep -q "Bad magic number in super-block" ); then
+	inactive_ver="un-initialized"
 else
-	rmdir ${tmpdir}
-	echo "mount inactive dev [${inactive_dev}] failed: ${errstr}"
-	exit 1
+	tmpdir=$(mktemp -d)
+	errstr=$(mount -o ro ${inactive_dev} ${tmpdir} 2>&1 1>/dev/null)
+	if [ $? -eq 0 ]; then
+		inactive_ver=$(awk -F= '/VERSION=/{print $2}' ${tmpdir}/${path} 2>&-)
+		umount ${tmpdir}
+		rmdir ${tmpdir}
+	else
+		rmdir ${tmpdir}
+		echo "mount inactive dev [${inactive_dev}] failed: ${errstr}"
+		exit 1
+	fi
 fi
 
 (
